"use client"


import { Inter } from 'next/font/google'
import '/app/styles/globals.css'
import styles from '/app/styles/page.module.css'

const inter = Inter({ subsets: ['latin'] })



import {NavCompo} from '/app/components/star'
import {PanelClass, MainClass} from '/app/components/class/star'
import Link from 'next/link'
import {user} from '/app/lib/user/user'
import { useLayoutEffect, useState } from 'react'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [u, setU] = useState({})
  useLayoutEffect(()=>{
    setInterval(()=>{
      user().then((i)=>{
        setU(i)
      })
    }, 100)
  },[])
  // console.log(u)
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainClass>
          <PanelClass>
            <Link className={styles.button} id='l' href="/" scroll={true}>Home</Link>
            {
        u.isLogin == false ? <Link className={styles.button} id='r' href="/login" scroll={true}>Login</Link> : <Link className={styles.button} id='r' href="/me" scroll={true}>me</Link>
    }
          </PanelClass>{children}</MainClass>
        </body>
    </html>
  )
}
